mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'',include('quizzabo.urls')),
]

quizzabo/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.price_list, name='price_list'),
]

quizzabo/models.py
from django.db import models

# Create your models here.

class Pricing(models.Model):
       
    PRICING_TYPE = (
        ('FREE', 'FREE'),
        ('EASY', 'EASY'),
        ('MEDIUM', 'MEDIUM'),
        ('EXPERT', 'EXPERT'),
        
    )

    type = models.CharField(
        max_length=20,
        choices= PRICING_TYPE,
        default='FREE',
    )
    
    price = models.CharField(max_length=20)
       
    
    class Meta:
        verbose_name_plural='Prices'

    def __str__(self):
        return self.type

    


class Item(models.Model):
    
    description=models.CharField(max_length=30,blank=True,null=False)
    pricing=models.ForeignKey(Pricing)

    def __str__(self):
        return self.description + '(' + self.pricing.type + ')'

quizzabo/views.py
from django.shortcuts import render
from . models import Pricing

# Create your views here.

def price_list(request):
	all_pricing=Pricing.objects.all()
	return render(request,'quizzabo/price_list.html',{'all_pricing': all_pricing})

quizzabo/templates/quizzabo/test.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
	<title>Pricing</title>

</head>
<body >


					{% for pricing in all_pricing %}

								<h3 class="title">{{ pricing.type}}</h3>
								<span class="price-value">{{ pricing.price }}</span>
							</div>
								<ul >
					        	
						        	{% for item in pricing.item_set.all%}
						        		<li>{{item.description}}</li>

						        	{% endfor%}
							</ul>
						</div>

					{% endfor %}


</body>
</html>